apiVersion: v1  
kind: Service
metadata:
  name: fullstack-app-postgres
  labels:
    app: fullstack-app-postgres
spec:
  type: NodePort
  selector:
    app: fullstack-app-postgres
  ports: 
  - name: http
    port: 8080
    targetPort: 8080