apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: fullstack_api
  
  DB_HOST: fullstack-postgres
  DB_DRIVER: postgres
  API_SECRET: 98hbun98h
  DB_USER: user
  DB_PASSWORD: password
  DB_NAME: fullstack_api
  DB_PORT: "5432"