name: Issue comment workflow

on:
  issue_comment:
    types: [created]

jobs:
  deploy-to-dev:
    name: Github Actions Comment
    if: github.event.comment.body == '/dev-deploy'
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Print the comment event
        run: |
          echo "Comment Received"
          echo ${{github.event.issue.pull_request}}
          echo ${{github.event.comment.body}}
      - name: Get latest commit of the PR
        id: get-pr-latest-commit
        run: |
          echo getting latest commit
      - name: Trigger webhook
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://65673aff-a13a-40d8-9011-9429597e9845.mock.pstmn.io/api/40/webhook/e8JyC1BQgqLJK99F1T6arfbxJpCghPCX'
          method: 'POST'
          data: >
            {
                "id": "1234"
            }     